services:

  postgres:
    networks:
      - elogiq_net
    container_name: postgres
    image: bistaff95/elogiqpg:$IMAGE_TAG
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "8001:5432"

  backend:
    networks:
      - elogiq_net
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${IMAGE_NAME}
    command: ["./run_be.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres

# Docker creates a volume with that name and a directory on disk
volumes:
  postgres_data:

networks:
  elogiq_net:
    driver: bridge